# Generated by Django 2.2.7 on 2019-12-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_description', models.CharField(max_length=100)),
                ('second_description', models.CharField(max_length=100)),
            ],
        ),
    ]
